source ~/.config/zsh/plugins.zsh
source ~/.config/zsh/env.zsh
source ~/.config/zsh/aliaes.zsh
source ~/.zim/modules/fzf-tab/fzf-tab.plugin.zsh
autopair-init

# mac extension
source ~/.config/zsh/mac/open.zsh

# useful tools
source ~/.config/zsh/tools.zsh

### RANDOM COLOR SCRIPT
#/opt/shell-color-scripts/colorscripts/00default.sh
### RANDOM COLOR SCRIPT ###
#colorscript random
